import type { Metadata } from 'next';
import { Lato } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import MainLayout from '@/components/providers/Main';

const lato = Lato({
    variable: '--font-lato',
    subsets: ['latin'],
    weight: ['700', '900'],
});

export const metadata: Metadata = {
    title: 'Job Portal | Webbiks LLC',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={cn('antialiased', lato.variable)}>
                <MainLayout>{children}</MainLayout>
            </body>
        </html>
    );
}
