import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import MainLayout from '@/components/providers/Main';

const roboto = Roboto({
    variable: '--font-roboto',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Job Portal | Webbiks LLC',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={cn('antialiased', roboto.variable)}>
                <MainLayout>{children}</MainLayout>
            </body>
        </html>
    );
}
